name: Gather indev
on:
    workflow_dispatch:
        # no params
jobs:
    gather-indev:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2

          - name: Post link
            if: 'false'
            env:
                DEPLOY_STATUS_WEBHOOK: ${{secrets.DEPLOY_STATUS_WEBHOOK}}
            run: |
                link="${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}"
                message="[GATHER indev] Hello <$link>"
                ./ci/deploy/call_webhook.sh "$message"

          - name: Kek
            run: |
                git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
                git config --local user.name "github-actions[bot]"

                git remote add upstream https://github.com/skyrim-platform/skymp

                git checkout -b indev

                echo kek > kek
                git add kek
                git commit -m 'kek!!!'

                git log --stat

                # maybe also https://stackoverflow.com/a/14947958
                git fetch origin pull/610/head
                git merge origin/pull/610/head

                git remote -vv
                git push -u origin indev -f
